
import { CircuitReport, SimulationData } from '../../../types';
import { GoogleGenAI, Type } from "@google/genai";

const enhanceReportWithAI = async (
    sections: any,
    data: SimulationData | null
): Promise<any> => {
    const apiKey = process.env.API_KEY;
    if (!apiKey) return sections;

    try {
        const ai = new GoogleGenAI({ apiKey });
        
        // Prepare Context
        const measurements = data?.measurements || {};
        const measurementStr = Object.entries(measurements)
            .map(([k, v]) => `${k}: ${v.toExponential(3)}`)
            .join(', ');
        
        const variablesStr = data?.variables?.join(', ') || 'None';

        const prompt = `
        You are an expert Senior Electronics Engineer and Technical Editor.
        
        YOUR TASK:
        Enhance the content of the following circuit analysis report sections. 
        The draft sections were generated by an automated checker. 
        You must rewrite them to be more detailed, professional, and insightful, incorporating the provided raw simulation data where relevant to back up claims.

        CONTEXT DATA (SIMULATION RESULTS):
        - Measurements: [${measurementStr}]
        - Tracked Variables: [${variablesStr}]

        DRAFT SECTIONS TO ENHANCE:
        ${JSON.stringify(sections, null, 2)}

        GUIDELINES:
        1. **Precision**: If the draft mentions "high voltage", check the measurements and insert the exact value (e.g., "Peak voltage reached 24.5V").
        2. **Tone**: Use professional engineering language (e.g., "Signal integrity", "Thermal runaway", "Bias point").
        3. **Formatting**: Use Markdown. Use bolding for key values. Use lists for multiple points.
        4. **Completeness**: If a section is empty but you see concerning data in measurements (e.g. huge currents), add a note in 'problems' or 'warnings'.
        5. **Structure**: Return a JSON object matching the requested schema exactly.

        Output ONLY the JSON.
        `;

        const response = await ai.models.generateContent({
            model: 'gemma-3-27b-it',
            contents: prompt,
            config: {
                responseMimeType: 'application/json',
                responseSchema: {
                    type: Type.OBJECT,
                    properties: {
                        overall: { type: Type.STRING },
                        problems: { type: Type.STRING },
                        recommendations: { type: Type.STRING },
                        warnings: { type: Type.STRING },
                        cautions: { type: Type.STRING }
                    }
                }
            }
        });

        if (response.text) {
            const enhancedSections = JSON.parse(response.text);
            // Merge back, preferring enhanced, but keep original if enhanced is missing/empty and original wasn't
            const result: any = { ...sections };
            Object.keys(enhancedSections).forEach(key => {
                if (enhancedSections[key]) {
                    result[key] = enhancedSections[key];
                }
            });
            return result;
        }
    } catch (e) {
        console.error("AI Report Enhancement Failed:", e);
    }
    
    return sections;
};

export const handleSubmitCircuitReport = async (
    args: any,
    actions: { addReport: (r: CircuitReport) => void },
    simulationResults: SimulationData | null
) => {
    let sections = args.sections || {};

    console.log("Submitting report...", sections);

    // Apply AI Enhancement Layer
    // We do this server-side (or client-side here via SDK) before saving to make the report permanent and high-quality.
    sections = await enhanceReportWithAI(sections, simulationResults);

    const report: CircuitReport = {
        id: crypto.randomUUID(),
        timestamp: Date.now(),
        title: args.title || "Untitled Report",
        summary: args.summary || "No summary provided.",
        tags: args.tags || [],
        sections: {
            overall: sections.overall || "",
            problems: sections.problems || "",
            recommendations: sections.recommendations || "",
            warnings: sections.warnings || "",
            cautions: sections.cautions || ""
        },
        measurements: simulationResults?.measurements || {},
        simulationData: simulationResults || undefined // Capture full data for graphs
    };

    actions.addReport(report);

    return { 
        message: "Report generated, enhanced by AI, and saved successfully.",
        reportId: report.id,
        link: "View in Report History"
    };
};
